---
schema-version: '1.0'
build:
  name: OpenSearch
  version: 2.11.1
ci:
  image:
    name: opensearchstaging/ci-runner:ci-runner-centos7-opensearch-build-v3
    args: -e JAVA_HOME=/opt/java/openjdk-17
components:
  - name: OpenSearch
    repository: https://github.com/opensearch-project/OpenSearch.git
    ref: 58af58d31b0b0af7edc0697a2b5a0316f235060e
    checks:
      - gradle:publish
      - gradle:properties:version
  - name: common-utils
    repository: https://github.com/opensearch-project/common-utils.git
    ref: eae4612b234916fcbbef57b8e041d3ecdb487620
    platforms:
      - linux
      - windows
    checks:
      - gradle:publish
      - gradle:properties:version
  - name: job-scheduler
    repository: https://github.com/opensearch-project/job-scheduler.git
    ref: 40cae432b3ee10d1fb704dccc6a7bd4a6bfebb3c
    platforms:
      - linux
      - windows
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version
  - name: security
    repository: https://github.com/opensearch-project/security.git
    ref: 2dab119387212d5047062100f799934b7ffbffea
    platforms:
      - linux
      - windows
  - name: k-NN
    repository: https://github.com/opensearch-project/k-NN.git
    ref: ad82097605b089c04b7a4e10c4e12d20614933fa
    platforms:
      - linux
      - windows
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version
  - name: geospatial
    repository: https://github.com/opensearch-project/geospatial.git
    ref: 7290a3e0df87d068edc5e71270ef28425ead86c2
    platforms:
      - linux
      - windows
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version
  - name: cross-cluster-replication
    repository: https://github.com/opensearch-project/cross-cluster-replication.git
    ref: 68af060bce1cacc5344cac72ccbe13bfdcd33b27
    platforms:
      - linux
      - windows
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version
  - name: ml-commons
    repository: https://github.com/opensearch-project/ml-commons.git
    ref: 17181b74f946f308a5bff9cfea5df0ad298ad556
    platforms:
      - linux
      - windows
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version: opensearch-ml-plugin
  - name: neural-search
    repository: https://github.com/opensearch-project/neural-search.git
    ref: 7368edcfd36c4a7d703d092fc2f73fa6c82f1d92
    platforms:
      - linux
      - windows
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version
  - name: notifications-core
    repository: https://github.com/opensearch-project/notifications.git
    ref: e47fc48051b34886bccbc77b30943dae141288d7
    platforms:
      - linux
      - windows
    working_directory: notifications
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version: opensearch-notifications-core
  - name: notifications
    repository: https://github.com/opensearch-project/notifications.git
    ref: e47fc48051b34886bccbc77b30943dae141288d7
    platforms:
      - linux
      - windows
    working_directory: notifications
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version: notifications
  - name: opensearch-observability
    repository: https://github.com/opensearch-project/observability.git
    ref: 934521d0d051ba55ae71c19cbc470d3a3ce45456
    platforms:
      - linux
      - windows
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version
  - name: opensearch-reports
    repository: https://github.com/opensearch-project/reporting.git
    ref: bd0ba2f4250fddf341b1021c1e96deea6f773dff
    platforms:
      - linux
      - windows
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version
  - name: sql
    repository: https://github.com/opensearch-project/sql.git
    ref: ddb2a21a836ea644ca4c3c8e755c2828aff84ec0
    platforms:
      - linux
      - windows
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version: opensearch-sql-plugin
  - name: asynchronous-search
    repository: https://github.com/opensearch-project/asynchronous-search.git
    ref: bb228912b132925bce5b9ae10a66e0c10fd4393f
    platforms:
      - linux
      - windows
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version
  - name: anomaly-detection
    repository: https://github.com/opensearch-project/anomaly-detection.git
    ref: fec39ca9d736274b12c50e9f3d2a43bc3beb9601
    platforms:
      - linux
      - windows
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version
  - name: alerting
    repository: https://github.com/opensearch-project/alerting.git
    ref: 2e37dfae11fc5aff24cb82de6f26d6a4be24dba2
    platforms:
      - linux
      - windows
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version: alerting
  - name: security-analytics
    repository: https://github.com/opensearch-project/security-analytics.git
    ref: 29f2cae5cbd755d41ea72ad2a9b60f9f3639a539
    platforms:
      - linux
      - windows
    checks:
      - gradle:properties:version
  - name: index-management
    repository: https://github.com/opensearch-project/index-management.git
    ref: 7b8b6b549842f9c09a6ddb005b72388ae0655b08
    platforms:
      - linux
      - windows
    checks:
      - gradle:properties:version
  - name: performance-analyzer
    repository: https://github.com/opensearch-project/performance-analyzer.git
    ref: eeec44a9cdc666da632632d180251feb14df7bbb
    platforms:
      - linux
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version
  - name: custom-codecs
    repository: https://github.com/opensearch-project/custom-codecs.git
    ref: 486ed652b7de41c34d81d8d663ca02302fed78ae
    platforms:
      - linux
      - windows
    checks:
      - gradle:properties:version
      - gradle:dependencies:opensearch.version
